//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolymerTutorialBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CupcakeVotes
    {
        public int VoteID { get; set; }
        public string PersonName { get; set; }
        public string Flavour { get; set; }
        public string Suggestions { get; set; }
    }
}
